### ISSUE TITLE
cannot find animatediff

### ISSUE THREAD

**Issue by GitRyan001** [s9roll7/animatediff-cli-prompt-travel#119]
Set Gradio Queue: True
[-] ADetailer initialized. version: 23.10.1, num models: 15
*** Error loading script: test_persistent.py
    Traceback (most recent call last):
      File "/root/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/root/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/root/stable-diffusion-webui/extensions/animatediff-cli-prompt-travel/scripts/test_persistent.py", line 3, in <module>
        from animatediff import get_dir
    ModuleNotFoundError: No module named 'animatediff'

---

**Comment by s9roll7** [comment]
this is not webui extension
