### ISSUE TITLE
ImportError: cannot import name 'maybe_allow_in_graph' from 'diffusers.utils'

### ISSUE THREAD

**Issue by rehypothecation** [s9roll7/animatediff-cli-prompt-travel#34]
While trying to set up the animatediff-cli project following the installation steps, I got an ImportError when running the animatediff --help command. 

I did the following:
    Cloned the repository using git clone https://github.com/neggles/animatediff-cli
    Created a virtual environment using python3.10 -m venv .venv
    Activated the virtual environment with source .venv/bin/activate
    Installed Torch and other dependencies as per the instructions.
    Ran animatediff --help

Received an ImportError with the following traceback:

```
Traceback (most recent call last):
  File "/home/user/Deep-Learning/Stable Diffusion/animatediff-cli/.venv/bin/animatediff", line 7, in <module>
    from animatediff.cli import cli
  File "/home/user/Deep-Learning/Stable Diffusion/animatediff-cli/src/animatediff/cli.py", line 12, in <module>
    from animatediff.generate import create_pipeline, run_inference
  File "/home/user/Deep-Learning/Stable Diffusion/animatediff-cli/src/animatediff/generate.py", line 13, in <module>
    from animatediff.models.unet import UNet3DConditionModel
  File "/home/user/Deep-Learning/Stable Diffusion/animatediff-cli/src/animatediff/models/unet.py", line 18, in <module>
    from .unet_blocks import (
  File "/home/user/Deep-Learning/Stable Diffusion/animatediff-cli/src/animatediff/models/unet_blocks.py", line 9, in <module>
    from animatediff.models.attention import Transformer3DModel
  File "/home/user/Deep-Learning/Stable Diffusion/animatediff-cli/src/animatediff/models/attention.py", line 10, in <module>
    from diffusers.utils import BaseOutput, maybe_allow_in_graph
ImportError: cannot import name 'maybe_allow_in_graph' from 'diffusers.utils'
```
Environment:

    OS: Ubuntu
    Python Version: 3.10
    Torch Version: 2.0.1+cu118

Would appreciate any help, thanks.

**Comment by rehypothecation** [comment]
Solved by installing an older version of diffusers.

```pip install diffusers==0.18.2```
