### ISSUE TITLE
Unable to run it on colab 

### ISSUE THREAD

**Issue by Clicli99** [s9roll7/animatediff-cli-prompt-travel#66]
I’m using a colab

Error loading script: test_persistent.py
    Traceback (most recent call last):
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 382, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/animatediff-cli-prompt-travel/scripts/test_persistent.py", line 3, in <module>
        from animatediff import get_dir
    ModuleNotFoundError: No module named 'animatediff'

**Comment by s9roll7** [comment]
this is not webui extension

**Comment by Clicli99** [comment]
Oh shoot, ok.thanks for response. 
 Is it possible to download it on colab ? What’s the method ?

**Comment by s9roll7** [comment]
I haven't tried it though, I found a colab that someone made.
I heard this one works.
https://colab.research.google.com/drive/1QVxBjAamxOIAAlSohQklZltRPx8WsxEN
